name: Publish crate to crates.io 

on:
  push:
    tags:
      - v(\d+\.\d+\.\d+)(.*)
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Publish to crates.io
        working-directory: crates/mdi
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}